### ISSUE TITLE
Nazwa aplikacji powinna może bardziej oddawać jej zastosowanie

### ISSUE THREAD

**Issue by rfilipczak** [mikoogla9/eventy2#14]
https://github.com/mikoogla9/eventy2/blob/3b3c2c02b493fe4594541ccb57bafdd4e5dd27ec/src/app/navbar/navbar.component.html#L2

"Events" mało mówi i nie odnosi się do zapisywania się na wydarzenia na Dniach Informatyki.

**Comment by mikoogla** [comment]
Przerobione w commit "added favicon + navbar text edited"
